### ISSUE TITLE
如何配置？

### ISSUE THREAD

**Issue by Jayin** [fritx/share.wx#1]
哪儿配置appid,app key 等微信公众号的相关参数？

**Comment by fritx** [comment]
<img width="300" src="https://user-images.githubusercontent.com/6647633/27525756-16ed4c3a-5a73-11e7-89a6-b74b9c8d0fbd.png">

Hi @Jayin ，在readme有提到mp.wx，是后端部分，那里的[config.js](https://github.com/fritx/mp.wx/blob/dev/config.sample.js)里配置appId和secret。

然后回到share.wx中的[config.js](https://github.com/fritx/share.wx/blob/master/config.sample.js)和[tongji.js](https://github.com/fritx/share.wx/blob/master/static/tongji.sample.js)，分别配置后端url及页面ga。

<img width="200" src="https://user-images.githubusercontent.com/6647633/27525774-3fd899ba-5a73-11e7-8968-648748b5a7c8.png">
