### ISSUE TITLE
能问下你项目首页上的那两个 gif 图片是用什么软件做的吗？

### ISSUE THREAD

**Issue by qiu8310** [fritx/share.wx#2]
【不知道在哪问，就提个 issues 吧】

**Comment by fritx** [comment]
<img width=200 src=https://user-images.githubusercontent.com/6647633/33938531-d0c647ce-e042-11e7-8d7f-1b27993a2dbf.png>

哦，我Mac上用的`licecap`这个app，生成gif动图

**Comment by qiu8310** [comment]
好的，谢谢了！
